### ISSUE TITLE
PermissionDenied exception thrown when admin tries to access course in LTI mode

### ISSUE THREAD

**Issue by chrisrrowland** [tl-its-umich-edu/my-learning-analytics#1099]
### Expected behavior (A description of what you expected to happen) : 
I'm not sure what the expected behavior is in canvas but I wouldn't expect a stack trace in the log

### Describe the bug (Tell us what happens instead of the expected behavior) :
When browsing to a course in canvas while logged in as myself (admin) I get a "Something went wrong" error and an exception is thrown in the log.

![image](https://user-images.githubusercontent.com/17617998/94706861-bbcbfc80-0310-11eb-9dc9-1087bef3173e.png)

```
student_dashboard  | [2020-09-30 11:28:31 -0400] [INFO] [basehttp.py:157] "GET /api/v1/courses/335188/info HTTP/1.1" 301 0
student_dashboard  | [2020-09-30 11:28:31 -0400] [WARNING] [log.py:222] Forbidden (Permission denied): /api/v1/courses/335188/info/
student_dashboard  | Traceback (most recent call last):
student_dashboard  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
student_dashboard  |     response = get_response(request)
student_dashboard  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
student_dashboard  |     response = self.process_exception_by_middleware(e, request)
student_dashboard  |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
student_dashboard  |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
student_dashboard  |   File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
student_dashboard  |     return view_func(request, *args, **kwargs)
student_dashboard  |   File "/usr/local/lib/python3.8/site-packages/rules/contrib/views.py", line 215, in _wrapped_view
student_dashboard  |     raise PermissionDenied()
student_dashboard  | django.core.exceptions.PermissionDenied

```

**Comment by jennlove-um** [comment]
The error message could be because the user didn't have admin access in both MyLA and Canvas.  Further research needed and discussion on whether to make Canvas admins MyLA admins by default.
