### ISSUE TITLE
latest Webpack-cli package making build fail

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/my-learning-analytics#1184]
With the later version of the webpack-cli 4.3.0 the docker build is failing 

```
[webpack-cli] TypeError: compiler.getInfrastructureLogger is not a function
    at CLIPlugin.apply (/usr/src/app/node_modules/webpack-cli/lib/plugins/CLIPlugin.js:80:32)
    at webpack (/usr/src/app/node_modules/webpack/lib/webpack.js:47:13)
    at WebpackCLI.createCompiler (/usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js:1165:24)
    at async WebpackCLI.bundleCommand (/usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js:1292:20)
    at async Command.<anonymous> (/usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js:322:21)
    at async Promise.all (index 1)
    at async Command.<anonymous> (/usr/src/app/node_modules/webpack-cli/lib/webpack-cli.js:708:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! my-learning-analytics@ prod: `BABEL_ENV=production webpack --config webpack.config.js --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the my-learning-analytics@ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-05T16_21_41_509Z-debug.log
```

Currently the fix is to label it o 4.2.0 and later deal with the detailed root cause for this

**Comment by zqian** [comment]
build successful from localhost and test myla.
