### ISSUE TITLE
If course start date is after the due_date of first assignment, then old assignment view doesn't work

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1195]
Thank you for contributing to this project!

- Make sure to search the [issues](https://github.com/tl-its-umich-edu/my-learning-analytics/issues) for duplicates first!

### Expected behavior (A description of what you expected to happen) : 
Clicking on assignments shows the tool

### Describe the bug (Tell us what happens instead of the expected behavior) :
It was observed with the previous assignment tool, that if you had a course with a manually defined start date (or in a term) with a date that's after the first assignment due date it will cause an exception like.

The problem here is when this creates the assignments_in_course it uses the due_date from the assignments and some may lie outside of the week_list. This could probably be fixed by expanding either the week_list or doing this logic in the lambda differently.

```
[2021-01-08 16:09:40 -0500] [ERROR] [log.py:222] Internal Server Error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rules/contrib/views.py", line 221, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/dashboard/views.py", line 556, in assignments
    assignments_in_course = get_course_assignments(course_id)
  File "/code/dashboard/views.py", line 659, in get_course_assignments
    assignments_in_course['week']=assignments_in_course['calender_week'].apply(lambda x: 0 if x == 0 else week_list.index(x)+1)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/series.py", line 3848, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/lib.pyx", line 2329, in pandas._libs.lib.map_infer
  File "/code/dashboard/views.py", line 659, in <lambda>
    assignments_in_course['week']=assignments_in_course['calender_week'].apply(lambda x: 0 if x == 0 else week_list.index(x)+1)
ValueError: 13 is not in list
```

I don't know how important this is to fix if we're going to be disabling or removing this old assignment view but we've seen it a few times lately. 

### Steps to Reproduce :
1. Create a course in Canvas and set the date in the future (or set the date for the course in admin)
2. Have it have assignments in Canvas with due dates after this date
3. Go to assignment view

**Comment by jennlove-um** [comment]
I'm going to mark this as something we are not going to fix since no one uses the old AP view, and we plan to remove it in an upcoming release.
