### ISSUE TITLE
Exception in term calculating end date if term dates not defined

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/my-learning-analytics#1201]
### Expected behavior (A description of what you expected to happen) : 

In Model.py, the course date range are calculated in course_date_range function. 

### Describe the bug (Tell us what happens instead of the expected behavior) :

If a course end date is not defined, the code will calculate the end date from term end date using get_correct_date_end().

Then an error occurs in get_correct_date_end() when there is no term start date defined, with the if statement/
```

def get_correct_date_end(self):
        **if (self.date_end.year - self.date_start.year) > 1:**
            logger.info(f'{self.date_end.year} - {self.date_start.year} greater than 1 so setting end year to match start year.')
            return self.date_end.replace(year=self.date_start.year)
        else:
            return self.date_end

```

This is a problem reported from Oregon State, where there is no start date defined for term, but end date is defined for term.

This trigger the following error message in the log file:
```
[2020-12-07 12:03:37 -0600] [ERROR] [log.py:222] Internal Server Error: /api/v1/courses/1792031/info/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/rules/contrib/views.py", line 221, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/dashboard/views.py", line 135, in get_course_info
    course_start, course_end = course.course_date_range
  File "/code/dashboard/models.py", line 219, in course_date_range
    end = self.term.get_correct_date_end()
  File "/code/dashboard/models.py", line 41, in get_correct_date_end
    if (self.date_end.year - self.date_start.year) > 1:
AttributeError: 'NoneType' object has no attribute 'year'
````

### Steps to Reproduce :
1. create a term without a start date, but have a valid end date
2. create a course within that term, and without end date itself
3. add MyLA to the course
4. MyLA won't start and one will find the error message in the log file: `AttributeError: 'NoneType' object has no attribute 'year'`

**Comment by jennlove-um** [comment]
Testing passes: 
- Term with no start date but has an end date
- Course has a start date but no end date
