### ISSUE TITLE
Error after locally if DEBUG is set to False.

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/my-learning-analytics#1364]
### Describe the bug (Tell us what happens instead of the expected behavior) :

If you startup MyLA with the configuration `DJANGO_DEBUG` set as `False `(the new default after #1359) you get an error locally in development when you launch the page. (Stack trace below)

http://localhost:5001/

This sounds a little like this https://stackoverflow.com/questions/5836674/why-does-debug-false-setting-make-my-django-static-files-access-fail

But I'm not sure why it worked before? Maybe because we're using whitenoise in production? Maybe because we all had it set to true?

### Steps to Reproduce :
1. Don't set DJANGO_DEBUG or leave it out of the configuration
2. Try to startup and launch MyLA.

### Additional context (Add any other context about the problem here) :
```
student_dashboard        | [2022-04-06 15:59:12 -0400] [ERROR] [log.py:224] Internal Server Error: /
student_dashboard        | Traceback (most recent call last):
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
student_dashboard        |     response = get_response(request)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
student_dashboard        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
student_dashboard        |   File "/code/dashboard/views.py", line 61, in get_home_template
student_dashboard        |     return render(request, 'frontend/index.html')
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/shortcuts.py", line 19, in render
student_dashboard        |     content = loader.render_to_string(template_name, context, request, using=using)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader.py", line 62, in render_to_string
student_dashboard        |     return template.render(context, request)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
student_dashboard        |     return self.template.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 170, in render
student_dashboard        |     return self._render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
student_dashboard        |     return self.nodelist.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
student_dashboard        |     bit = node.render_annotated(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
student_dashboard        |     return self.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 150, in render
student_dashboard        |     return compiled_parent._render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 162, in _render
student_dashboard        |     return self.nodelist.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
student_dashboard        |     bit = node.render_annotated(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
student_dashboard        |     return self.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/loader_tags.py", line 62, in render
student_dashboard        |     result = block.nodelist.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 938, in render
student_dashboard        |     bit = node.render_annotated(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/base.py", line 905, in render_annotated
student_dashboard        |     return self.render(context)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/template/library.py", line 192, in render
student_dashboard        |     output = self.func(*resolved_args, **resolved_kwargs)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/webpack_loader/templatetags/webpack_loader.py", line 12, in render_bundle
student_dashboard        |     tags = utils.get_as_tags(bundle_name, extension=extension, config=config, attrs=attrs)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/webpack_loader/utils.py", line 64, in get_as_tags
student_dashboard        |     for chunk in bundle:
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/webpack_loader/utils.py", line 34, in _filter_by_extension
student_dashboard        |     for chunk in bundle:
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py", line 49, in filter_chunks
student_dashboard        |     url = self.get_chunk_url(files[chunk])
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/webpack_loader/loader.py", line 61, in get_chunk_url
student_dashboard        |     return staticfiles_storage.url(relpath)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
student_dashboard        |     return self._url(self.stored_name, name, force)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
student_dashboard        |     hashed_name = hashed_name_func(*args)
student_dashboard        |   File "/usr/local/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
student_dashboard        |     raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
student_dashboard        | ValueError: Missing staticfiles manifest entry for 'dist/main-4c375858d5b8b17bcfb2.js'
```

**Comment by jonespm** [comment]
Perhaps the fix for this is to comment that locally in development mode you *need* to set DJANGO_DEBUG to true. Probably should put this in the .hjson and also in the README, probably around step 6-7.

**Comment by jonespm** [comment]
I remember what I did for CAE was to put this in the environment for `docker-compose.yml`. We could also put `DJANGO_DEBUG=True` in our docker-compose environment. But that uses variables directly from the environment (no config). MyLA only reads from the config as we don't have #787. So this will have to be set manually by local developers. 

https://github.com/tl-its-umich-edu/canvas-app-explorer/blob/29af6ed2e351ae32f4781ba3b205553c270b480c/docker-compose.yml#L40
