### ISSUE TITLE
Extra Environment Argument Needed to Run "docker-compose build"

### ISSUE THREAD

**Issue by vjcao** [tl-its-umich-edu/my-learning-analytics#516]
Without setting DATA_WAREHOUSE_PORT to 5432, application will fail to build with this error:

Traceback (most recent call last):
  File "manage.py", line 16, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/dashboard/settings.py", line 147, in <module>
    'PORT': config('DATA_WAREHOUSE_PORT', default=5432, cast=int),
  File "/usr/local/lib/python3.6/site-packages/decouple.py", line 197, in __call__
    return self.config(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/decouple.py", line 85, in __call__
    return self.get(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/decouple.py", line 79, in get
    return cast(value)
ValueError: invalid literal for int() with base 10: ''
ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn global add wait-port@"~0.2.2" &&     yarn install &&     find /usr/lib/node_modules /code/node_modules -type d -name "examples" -print0 | xargs -0 rm -rf &&     echo yes | DJANGO_SECRET_KEY="collectstatic" python manage.py collectstatic --verbosity 0' returned a non-zero code: 1

**Comment by jonespm** [comment]
Thanks you should be able to comment that out and it will take the default port. It should have been commented out and optional as not all schools will load from a data warehouse and may do the ETL directly.

I plan to update the configuration file.
