### ISSUE TITLE
Can't start after pull

### ISSUE THREAD

**Issue by miller11** [tl-its-umich-edu/my-learning-analytics#553]
@jonespm I pulled down the latest and now I cant get the student_dashboard to start. I get a big stacktrace that I can't make sense of. 

`student_dashboard | [2019-06-21 14:19:09 -0400] [25] [ERROR] Exception in worker process
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
student_dashboard |     worker.init_process()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
student_dashboard |     self.load_wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
student_dashboard |     self.wsgi = self.app.wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
student_dashboard |     self.callable = self.load()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
student_dashboard |     return self.load_wsgiapp()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
student_dashboard |     return util.import_app(self.app_uri)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
student_dashboard |     __import__(module)
student_dashboard |   File "/code/dashboard/wsgi.py", line 16, in <module>
student_dashboard |     application = get_wsgi_application()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
student_dashboard |     django.setup(set_prefix=False)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
student_dashboard |     apps.populate(settings.INSTALLED_APPS)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
student_dashboard |     app_config = AppConfig.create(entry)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
student_dashboard |     mod = import_module(mod_path)
student_dashboard |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
student_dashboard |     return _bootstrap._gcd_import(name[level:], package, level)
student_dashboard | ModuleNotFoundError: No module named 'rules'
student_dashboard | [2019-06-21 14:19:09 -0400] [25] [INFO] Worker exiting (pid: 25)
student_dashboard | [2019-06-21 14:19:09 -0400] [29] [ERROR] Exception in worker process
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
student_dashboard |     worker.init_process()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
student_dashboard |     self.load_wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
student_dashboard |     self.wsgi = self.app.wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
student_dashboard |     self.callable = self.load()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
student_dashboard |     return self.load_wsgiapp()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
student_dashboard |     return util.import_app(self.app_uri)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
student_dashboard |     __import__(module)
student_dashboard |   File "/code/dashboard/wsgi.py", line 16, in <module>
student_dashboard |     application = get_wsgi_application()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
student_dashboard |     django.setup(set_prefix=False)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
student_dashboard |     apps.populate(settings.INSTALLED_APPS)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
student_dashboard |     app_config = AppConfig.create(entry)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
student_dashboard |     mod = import_module(mod_path)
student_dashboard |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
student_dashboard |     return _bootstrap._gcd_import(name[level:], package, level)
student_dashboard | ModuleNotFoundError: No module named 'rules'
student_dashboard | [2019-06-21 14:19:09 -0400] [29] [INFO] Worker exiting (pid: 29)
student_dashboard | [2019-06-21 14:19:09 -0400] [31] [ERROR] Exception in worker process
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
student_dashboard |     worker.init_process()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
student_dashboard |     self.load_wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
student_dashboard |     self.wsgi = self.app.wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
student_dashboard |     self.callable = self.load()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
student_dashboard |     return self.load_wsgiapp()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
student_dashboard |     return util.import_app(self.app_uri)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
student_dashboard |     __import__(module)
student_dashboard |   File "/code/dashboard/wsgi.py", line 16, in <module>
student_dashboard |     application = get_wsgi_application()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
student_dashboard |     django.setup(set_prefix=False)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
student_dashboard |     apps.populate(settings.INSTALLED_APPS)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
student_dashboard |     app_config = AppConfig.create(entry)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
student_dashboard |     mod = import_module(mod_path)
student_dashboard |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
student_dashboard |     return _bootstrap._gcd_import(name[level:], package, level)
student_dashboard | ModuleNotFoundError: No module named 'rules'
student_dashboard | [2019-06-21 14:19:09 -0400] [27] [ERROR] Exception in worker process
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
student_dashboard |     worker.init_process()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
student_dashboard |     self.load_wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
student_dashboard |     self.wsgi = self.app.wsgi()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
student_dashboard |     self.callable = self.load()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
student_dashboard |     return self.load_wsgiapp()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
student_dashboard |     return util.import_app(self.app_uri)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
student_dashboard |     __import__(module)
student_dashboard |   File "/code/dashboard/wsgi.py", line 16, in <module>
student_dashboard |     application = get_wsgi_application()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
student_dashboard |     django.setup(set_prefix=False)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
student_dashboard |     apps.populate(settings.INSTALLED_APPS)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 85, in populate
student_dashboard |     app_config = AppConfig.create(entry)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 120, in create
student_dashboard |     mod = import_module(mod_path)
student_dashboard |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
student_dashboard |     return _bootstrap._gcd_import(name[level:], package, level)
student_dashboard | ModuleNotFoundError: No module named 'rules'
student_dashboard | [2019-06-21 14:19:09 -0400] [27] [INFO] Worker exiting (pid: 27)
student_dashboard | [2019-06-21 14:19:09 -0400] [31] [INFO] Worker exiting (pid: 31)
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 210, in run
student_dashboard |     self.sleep()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 360, in sleep
student_dashboard |     ready = select.select([self.PIPE[0]], [], [], 1.0)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
student_dashboard |     self.reap_workers()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
student_dashboard |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
student_dashboard | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
student_dashboard | 
student_dashboard | During handling of the above exception, another exception occurred:
student_dashboard | 
student_dashboard | Traceback (most recent call last):
student_dashboard |   File "/usr/local/bin/gunicorn", line 10, in <module>
student_dashboard |     sys.exit(run())
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
student_dashboard |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 223, in run
student_dashboard |     super(Application, self).run()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 72, in run
student_dashboard |     Arbiter(self).run()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 232, in run
student_dashboard |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 345, in halt
student_dashboard |     self.stop()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 393, in stop
student_dashboard |     time.sleep(0.1)
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
student_dashboard |     self.reap_workers()
student_dashboard |   File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
student_dashboard |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
student_dashboard | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
`

**Comment by miller11** [comment]
My fault, I forgot to rebuild
