### ISSUE TITLE
CronJob is failing silently; AcademicTerms matching query does not exist

### ISSUE THREAD

**Issue by pelaprat** [tl-its-umich-edu/my-learning-analytics#770]
We're noticing that the data is not updating in MyLA even though the cronjob is running every 5 minutes. It looks like you only get useful information in the logs if you set the log level to DEBUG (you might want to change). Anyway, we're seeing this:

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django_cron/management/commands/runcrons.py", line 71, in run_cron_with_cache_check
manager.run(force)
File "/usr/local/lib/python3.6/site-packages/django_cron/__init__.py", line 215, in run
self.msg = self.cron_job.do()
File "/code/dashboard/cron.py", line 503, in do
status += self.update_course(course_verification.course_data)
File "/code/dashboard/cron.py", line 464, in update_course
course.term = AcademicTerms.objects.get(id=warehouse_course_df["enrollment_term_id"])
File "/usr/local/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
self.model._meta.object_name
dashboard.models.DoesNotExist: AcademicTerms matching query does not exist.
```

We're not sure how to fix this – but it's generating this error every time the cronjob runs.

**Comment by jonespm** [comment]
I know we have a silent failure on BigQuery failing #667 but haven't seen if it getting to update_course and failing. 

My guess is that this bug is related or the same as to #758 where the terms are only pulled based on the setting EARLIEST_TERM_DATE. If you have any terms that are before that date (or courses with terms like DEFAULT TERM) it will silently fail as you mention.

For the next minor release (2019.02.02) we'd plan to change it to pull in all the terms. Locally we worked around this by just only using terms that were after this EARLIEST_TERM_DATE.

This isn't a large fix, I think I can get it fix and merged into the 2019.02.x branch by early next week.

I agree there should be a try/except though around this entire process

**Comment by pelaprat** [comment]
Thanks – we'll wait until the next tag.

**Comment by rpfernandezjr** [comment]
This still seems to be happening. I was moving things around and tried connecting to a database that MyLA didn't have access too. It exited with a status code of 0 and the python stack trace was thrown, but it is logged as a DEBUG level message. 

```
DJANGO_LOG_LEVEL=DEBUG DJANGO_DEBUG=True DJANGO_TEMPLATE_DEBUG=true ROOT_LOG_LEVEL=DEBUG python ./manage.py runcrons --force | tee umn-cronjob.out
[2019-11-20 18:05:46 -0500] [58] [DEBUG] (0.000) None; args=None
[2019-11-20 18:05:46 -0500] [58] [DEBUG] (0.000) None; args=None
[2019-11-20 18:05:47 -0500] [58] [DEBUG] db-name:umn
[2019-11-20 18:05:47 -0500] [58] [DEBUG] db-user:myla_service
[2019-11-20 18:05:47 -0500] [58] [DEBUG] Running cron: DashboardCronJob code dashboard.DashboardCronJob
[2019-11-20 18:05:47 -0500] [58] [INFO] ** dashboard cron tab
[2019-11-20 18:05:47 -0500] [58] [DEBUG] in checking course
[2019-11-20 18:05:47 -0500] [58] [DEBUG] (0.000) None; args=()
[2019-11-20 18:05:47 -0500] [58] [DEBUG] select *
                        from course_dim c
                        where c.id = '43560000000108765'
                        
[2019-11-20 18:07:57 -0500] [58] [DEBUG] (0.001) None; args=['dashboard.DashboardCronJob', '2019-11-20 23:05:47.384828', '2019-11-20 23:07:57.990427', False, 'python3.6/site-packages/django/utils/six.py", line 685, in reraise\n    raise value.with_traceback(tb)\n  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection\n    self.connect()\n  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect\n    self.connection = self.get_new_connection(conn_params)\n  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection\n    connection = Database.connect(**conn_params)\n  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\ndjango.db.utils.OperationalError: could not connect to server: Connection timed out\n\tIs the server running on host "udw-prod-data-redshiftcluster-1h07s6m7ui13q.cgrfayd5ucy4.us-east-1.redshift.amazonaws.com" (52.207.197.11) and accepting\n\tTCP/IP connections on port 5439?\n\n', None]
```

I think we want to log these stack traces at an ERROR log level, so they aren't hidden.

```
python manage.py runcrons 
```

We should also exit with a non-zero exit status on failure. Since we are exiting with 0, some monitoring platforms wont detect that a problem occurred

**Comment by jennlove-um** [comment]
@rpfernandezjr Is this still an issue?  If not, we will go ahead and close this issue.  Thanks!

**Comment by jennlove-um** [comment]
I'm going to close this issue.  We have made a number of improvements in the cron and we no longer see this issue.
