### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by justin0022** [tl-its-umich-edu/my-learning-analytics#834]
## Expected behavior (A clear and concise description of what you expected to happen) : 
With latest master, getting a TypeError on homepage. Probably relates to https://github.com/tl-its-umich-edu/my-learning-analytics/commit/177816663c337f83740e3a75f3ead15a5c509ca3.

I updated my `env.json` `RESOURCE_VALUES` to:
```
{
        "files":  {"types": ["canvas"], "icon": "fas fa-file fa-lg"},
        "videos": {"types": ["leccap"], "icon": "fas fa-video fa-lg"}
},
```

## Describe the bug (Tell us what happens instead of the expected behavior) :
<img width="590" alt="Screen Shot 2020-01-03 at 9 44 06 AM" src="https://user-images.githubusercontent.com/8836578/71739246-c010cb00-2e0d-11ea-9645-45f3b9ecce0f.png">

## Steps to Reproduce :
1. Build latest master
2. Navigate to homepage

**Comment by jonespm** [comment]
Were you still getting this error after the config update or are you saying you had to update your config to get the error to go away?

**Comment by justin0022** [comment]
I was still getting the error after I changed my config.

**Comment by justin0022** [comment]
Here's the full Python error log:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 364, in resolve
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/code/dashboard/urls.py", line 30, in <module>
    from . import views
  File "/code/dashboard/views.py", line 43, in <module>
    for resource_type in value['types']:
```

**Comment by jonespm** [comment]
Yeah, hmm, I got that error too but change the config then I didn't get the error anymore. I'm seeing some formatting issue related to this patch but no errors. It should have been more protected against an configuration error though.

**Comment by jonespm** [comment]
I'm working on trying to simplify this configuration

**Comment by justin0022** [comment]
> Yeah, hmm, I got that error too but change the config then I didn't get the error anymore. I'm seeing some formatting issue related to this patch but no errors. It should have been more protected against an configuration error though.

Okay let me try, I'll report back.

**Comment by justin0022** [comment]
Are there any other env variables I should change? I just changed the `RESOURCE_VALUES` variable, but still getting the TypeError.

**Comment by jonespm** [comment]
I don't see anything different. I re-wrote the logic a little to make it a little safer and also got rid of the separate RESOURCE_URLS value (folding that into RESOURCE_ACCESS_CONFIG) in #835

**Comment by justin0022** [comment]
Hmm, strange. I'll try running your PR.

**Comment by justin0022** [comment]
I tried building the latest master on my work laptop and it works fine after I change the `env.json` with the new `RESOURCE_VALUES`. I'm still not sure why it wasn't working on my personal laptop (both Macs)... I'll close this now.

**Comment by pushyamig** [comment]
This is resolved for SPR/Summer 202 release.
